package com.example.radan_backend.service;

import com.example.radan_backend.Command;
import com.example.radan_backend.dto.MovieDTO;
import com.example.radan_backend.dto.MovieRequest;
import com.example.radan_backend.entity.Cast;
import com.example.radan_backend.entity.Genre;
import com.example.radan_backend.entity.Movie;
import com.example.radan_backend.repository.CastRepository;
import com.example.radan_backend.repository.GenreRepository;
import com.example.radan_backend.repository.MovieRepository;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class CreateMovieService implements Command<MovieRequest, MovieDTO> {

    private final MovieRepository movieRepository;
    private final FileStorageService fileStorageService;
    private final GenreRepository genreRepository;
    private final CastRepository castRepository;

    public CreateMovieService(MovieRepository movieRepository, FileStorageService fileStorageService, GenreRepository genreRepository, CastRepository castRepository) {
        this.movieRepository = movieRepository;
        this.fileStorageService = fileStorageService;
        this.genreRepository = genreRepository;
        this.castRepository = castRepository;
    }

    @Override
    public ResponseEntity<MovieDTO> execute(MovieRequest request) {
        // 1. Store the poster image file and get the unique filename
        String posterFileName = fileStorageService.storeFile(request.getPosterImage());

        // 2. Create a new Movie entity
        Movie movie = new Movie();
        movie.setTitle(request.getTitle());
        movie.setDuration(request.getDuration());
        movie.setSynopsis(request.getSynopsis());
        movie.setDirector(request.getDirector());

        // 3. Set the posterUrl to the path/filename generated by the storage service
        // You might want to store a full URL depending on your frontend setup
        // For example: "/uploads/posters/" + posterFileName
        movie.setPosterUrl(posterFileName);

        List<Genre> genres = genreRepository.findAllById(request.getGenreIds());
        movie.setGenres(genres);

        List<Cast> casts = castRepository.findAllById(request.getCastIds());
        movie.setCasts(casts);

        Movie savedMovie = movieRepository.save(movie);
        return ResponseEntity.status(HttpStatus.CREATED).body(new MovieDTO(savedMovie));
    }
}
